# Generated by Django 5.1.4 on 2024-12-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=10000)),
                ('employer_name', models.CharField(max_length=200)),
                ('employer_phone', models.CharField(max_length=30)),
                ('employer_email', models.CharField(max_length=100)),
                ('minimum_age', models.IntegerField(default=None, null=True)),
                ('min_pay', models.IntegerField(default=None, null=True)),
                ('max_pay', models.IntegerField(default=None, null=True)),
                ('date_created', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
