# Generated by Django 5.1.4 on 2025-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='admin_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
