# Generated by Django 5.1.4 on 2025-01-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_jobposting_admin_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='max_pay',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='min_pay',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='minimum_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
