# Generated by Django 5.1.4 on 2025-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_alter_jobposting_max_pay_alter_jobposting_min_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
